### ISSUE TITLE
Why I receive an error when I try to make lab9-dev?

### ISSUE THREAD

**Issue by onlyrains** [maZymaZe/OS2021#2]
> input: '../build/src/user/init' -> 'init'
input: '../build/src/user/cat' -> 'cat'
mkfs: ../src/user/mkfs/main.c:280: iappend: Assertion 'fbn < INODE_MAX_BLOCKS' failed.
Aborted (core dumped)
Traceback (most recent call last):
  File "./generate-image.py", line 62, in <module>
    generate_fs_image(fs_image, args.user_files)
  File "./generate-image.py", line 37, in generate_fs_image
    sh(f'../build/mkfs {target} {file_list}')
  File "./generate-image.py", line 11, in sh
    assert system(command) == 0
AssertionError
boot/CMakeFiles/image.dir/build.make:77: recipe for target 'boot/sd.img' failed
make[2]: *** [boot/sd.img] Error 1

The compile is good, but mkfs:280  `assert(fbn < INODE_MAX_BLOCKS);`  gave this error.

**Comment by maZymaZe** [comment]
```
cd build
make clean
make qemu
```
try this?
